# _config.yml

title: La vieille roue
author: CodeJBL
description: labo de rénovation de jantes et de restauration de véhicules anciens, prestige, collection, sport.
url: "https://lavieilleroue.fr"
baseurl: ""

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
# Ensure the generated images folder (starts with underscore) is copied to the site
include:
  - "assets/images/generated"

